spring:
  profile.active: dev, test, prod

  datasource:
    url: jdbc:postgresql://localhost:5432/topics_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}
